parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''

steps:
- task: HelmDeploy@0
  displayName: 'Add Service Catalog Helm Repo'
  enabled: true
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    arguments: 'add svc-cat https://svc-catalog-charts.storage.googleapis.com'