---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-disk
  namespace: artifactory
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artifactory-oss
  namespace: artifactory
spec:
  serviceName: "artifactory"
  replicas: 1
  selector:
    matchLabels:
      app: artifactory-oss
  template:
    metadata:
      labels:
        app: artifactory-oss
    spec:
      initContainers:
      - name: artifactory-init
        image: hmcts/cnp-artifactory-init:0.1
        command: ['sh', '-c', 'mkdir -p /var/opt/jfrog/artifactory/etc; cp artifactory.config.xml /var/opt/jfrog/artifactory/etc/; chown -R 1030:1030 /var/opt/jfrog/artifactory; chmod -R 0700 /var/opt/jfrog/artifactory;']
        volumeMounts:
        - mountPath: "/var/opt/jfrog/artifactory"
          name: artifactory-data
      containers:
      - image: docker.bintray.io/jfrog/artifactory-oss:6.4.1
        name: artifactory-oss
        env:
          - name: EXTRA_JAVA_OPTIONS
            value: '-Xms2g -Xmx8g'
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits:
            memory: "8192Mi"
            cpu: "3000m"
        ports:
        - containerPort: 8081
          name: http
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/var/opt/jfrog/artifactory"
          name: artifactory-data
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-disk
---
#
# Service
#
apiVersion: v1
kind: Service
metadata:
  name: artifactory-oss
  namespace: artifactory
  labels:
    app: artifactory-oss
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: artifactory-oss
