parameters:
  serviceConnection: ''

steps:

- task: HelmDeploy@0
  displayName: 'Initialise Helm Client'
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'init'
    arguments: '--client-only'

- task: HelmDeploy@0
  displayName: 'Delete Traefik'
  continueOnError: true
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: '${{ parameters.serviceConnection }}'
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'delete'
    arguments: '--purge traefik'

- task: HelmDeploy@0
  displayName: 'Install Traefik'
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'install'
    chartType: 'Name'
    chartName: 'stable/traefik'
    namespace: 'kube-system'
    releaseName: 'traefik'
    valueFile: 'helm/$(environment)/traefik.yml'

