helmOperator:
    create: true
    chartsSyncInterval: 1m
registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/cnp-flux-config
  path: k8s/preview,k8s/common
  label: preview
  pollInterval: 1m