parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  helmVersion: ''
  
steps:
- task: HelmInstaller@0
  displayName: 'Install Helm ${{ parameters.helmVersion }}'
  inputs:
      helmVersion: ${{ parameters.helmVersion }}
      installKubectl: false

- task: HelmDeploy@0
  displayName: 'Initialise Helm Client'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: ${{ parameters.aksResourceGroup }}
    kubernetesCluster: ${{ parameters.aksClusterName }}
    command: 'init'
    arguments: '--client-only'